// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// A rigid transform, flattened as a 16-element row-major matrix
/// (matches `Matrix4.storage` / `Matrix4.fromList`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PoseMessage: Hashable, CustomStringConvertible {
  var matrix: [Double]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PoseMessage? {
    let matrix = pigeonVar_list[0] as! [Double]

    return PoseMessage(
      matrix: matrix
    )
  }
  func toList() -> [Any?] {
    return [
      matrix
    ]
  }
  static func == (lhs: PoseMessage, rhs: PoseMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.matrix, rhs.matrix)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PoseMessage")
    MessagesPigeonInternal.deepHash(value: matrix, hasher: &hasher)
  }

  public var description: String {
    return "PoseMessage(matrix: \(String(describing: matrix)))"
  }
}

/// One entry from an `ARSessionManager.onPlaneOrPointTap` hit test.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HitTestResultMessage: Hashable, CustomStringConvertible {
  /// Mirrors `ARHitTestResultType` (0 = undefined, 1 = plane, 2 = point).
  var type: Int64
  var distance: Double
  var worldTransform: [Double]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HitTestResultMessage? {
    let type = pigeonVar_list[0] as! Int64
    let distance = pigeonVar_list[1] as! Double
    let worldTransform = pigeonVar_list[2] as! [Double]

    return HitTestResultMessage(
      type: type,
      distance: distance,
      worldTransform: worldTransform
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      distance,
      worldTransform,
    ]
  }
  static func == (lhs: HitTestResultMessage, rhs: HitTestResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.distance, rhs.distance) && MessagesPigeonInternal.deepEquals(lhs.worldTransform, rhs.worldTransform)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HitTestResultMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: distance, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: worldTransform, hasher: &hasher)
  }

  public var description: String {
    return "HitTestResultMessage(type: \(String(describing: type)), distance: \(String(describing: distance)), worldTransform: \(String(describing: worldTransform)))"
  }
}

/// Mirrors `ARNode.toMap()` / `ARNode.fromMap()`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NodeMessage: Hashable, CustomStringConvertible {
  /// Mirrors `NodeType.index`.
  var type: Int64
  var name: String
  var transformation: [Double]
  var uri: String? = nil
  var data: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NodeMessage? {
    let type = pigeonVar_list[0] as! Int64
    let name = pigeonVar_list[1] as! String
    let transformation = pigeonVar_list[2] as! [Double]
    let uri: String? = nilOrValue(pigeonVar_list[3])
    let data: [String?: Any?]? = nilOrValue(pigeonVar_list[4])

    return NodeMessage(
      type: type,
      name: name,
      transformation: transformation,
      uri: uri,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      name,
      transformation,
      uri,
      data,
    ]
  }
  static func == (lhs: NodeMessage, rhs: NodeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.transformation, rhs.transformation) && MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri) && MessagesPigeonInternal.deepEquals(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NodeMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transformation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: data, hasher: &hasher)
  }

  public var description: String {
    return "NodeMessage(type: \(String(describing: type)), name: \(String(describing: name)), transformation: \(String(describing: transformation)), uri: \(String(describing: uri)), data: \(String(describing: data)))"
  }
}

/// Mirrors `ARAnchor.toJson()` / `ARAnchor.fromJson()` (currently only
/// `ARPlaneAnchor` is implemented natively; `ARUnkownAnchor` is a
/// forward-compatible placeholder for anchor types future native code may
/// add, hence the mostly-nullable fields below).
///
/// Generated class from Pigeon that represents data sent in messages.
struct AnchorMessage: Hashable, CustomStringConvertible {
  /// Mirrors `AnchorType.index` (0 = plane).
  var type: Int64
  var name: String
  var transformation: [Double]
  var childNodes: [String?]? = nil
  var cloudAnchorId: String? = nil
  var ttl: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnchorMessage? {
    let type = pigeonVar_list[0] as! Int64
    let name = pigeonVar_list[1] as! String
    let transformation = pigeonVar_list[2] as! [Double]
    let childNodes: [String?]? = nilOrValue(pigeonVar_list[3])
    let cloudAnchorId: String? = nilOrValue(pigeonVar_list[4])
    let ttl: Int64? = nilOrValue(pigeonVar_list[5])

    return AnchorMessage(
      type: type,
      name: name,
      transformation: transformation,
      childNodes: childNodes,
      cloudAnchorId: cloudAnchorId,
      ttl: ttl
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      name,
      transformation,
      childNodes,
      cloudAnchorId,
      ttl,
    ]
  }
  static func == (lhs: AnchorMessage, rhs: AnchorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.transformation, rhs.transformation) && MessagesPigeonInternal.deepEquals(lhs.childNodes, rhs.childNodes) && MessagesPigeonInternal.deepEquals(lhs.cloudAnchorId, rhs.cloudAnchorId) && MessagesPigeonInternal.deepEquals(lhs.ttl, rhs.ttl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnchorMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transformation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: childNodes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cloudAnchorId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ttl, hasher: &hasher)
  }

  public var description: String {
    return "AnchorMessage(type: \(String(describing: type)), name: \(String(describing: name)), transformation: \(String(describing: transformation)), childNodes: \(String(describing: childNodes)), cloudAnchorId: \(String(describing: cloudAnchorId)), ttl: \(String(describing: ttl)))"
  }
}

/// Arguments for `ARSessionManager.onInitialize`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SessionConfigMessage: Hashable, CustomStringConvertible {
  var showAnimatedGuide: Bool
  var showFeaturePoints: Bool
  /// Mirrors `PlaneDetectionConfig.index`.
  var planeDetectionConfig: Int64
  var showPlanes: Bool
  var customPlaneTexturePath: String? = nil
  var showWorldOrigin: Bool
  var handleTaps: Bool
  var handlePans: Bool
  var handleRotation: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionConfigMessage? {
    let showAnimatedGuide = pigeonVar_list[0] as! Bool
    let showFeaturePoints = pigeonVar_list[1] as! Bool
    let planeDetectionConfig = pigeonVar_list[2] as! Int64
    let showPlanes = pigeonVar_list[3] as! Bool
    let customPlaneTexturePath: String? = nilOrValue(pigeonVar_list[4])
    let showWorldOrigin = pigeonVar_list[5] as! Bool
    let handleTaps = pigeonVar_list[6] as! Bool
    let handlePans = pigeonVar_list[7] as! Bool
    let handleRotation = pigeonVar_list[8] as! Bool

    return SessionConfigMessage(
      showAnimatedGuide: showAnimatedGuide,
      showFeaturePoints: showFeaturePoints,
      planeDetectionConfig: planeDetectionConfig,
      showPlanes: showPlanes,
      customPlaneTexturePath: customPlaneTexturePath,
      showWorldOrigin: showWorldOrigin,
      handleTaps: handleTaps,
      handlePans: handlePans,
      handleRotation: handleRotation
    )
  }
  func toList() -> [Any?] {
    return [
      showAnimatedGuide,
      showFeaturePoints,
      planeDetectionConfig,
      showPlanes,
      customPlaneTexturePath,
      showWorldOrigin,
      handleTaps,
      handlePans,
      handleRotation,
    ]
  }
  static func == (lhs: SessionConfigMessage, rhs: SessionConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.showAnimatedGuide, rhs.showAnimatedGuide) && MessagesPigeonInternal.deepEquals(lhs.showFeaturePoints, rhs.showFeaturePoints) && MessagesPigeonInternal.deepEquals(lhs.planeDetectionConfig, rhs.planeDetectionConfig) && MessagesPigeonInternal.deepEquals(lhs.showPlanes, rhs.showPlanes) && MessagesPigeonInternal.deepEquals(lhs.customPlaneTexturePath, rhs.customPlaneTexturePath) && MessagesPigeonInternal.deepEquals(lhs.showWorldOrigin, rhs.showWorldOrigin) && MessagesPigeonInternal.deepEquals(lhs.handleTaps, rhs.handleTaps) && MessagesPigeonInternal.deepEquals(lhs.handlePans, rhs.handlePans) && MessagesPigeonInternal.deepEquals(lhs.handleRotation, rhs.handleRotation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SessionConfigMessage")
    MessagesPigeonInternal.deepHash(value: showAnimatedGuide, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showFeaturePoints, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: planeDetectionConfig, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showPlanes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: customPlaneTexturePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showWorldOrigin, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: handleTaps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: handlePans, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: handleRotation, hasher: &hasher)
  }

  public var description: String {
    return "SessionConfigMessage(showAnimatedGuide: \(String(describing: showAnimatedGuide)), showFeaturePoints: \(String(describing: showFeaturePoints)), planeDetectionConfig: \(String(describing: planeDetectionConfig)), showPlanes: \(String(describing: showPlanes)), customPlaneTexturePath: \(String(describing: customPlaneTexturePath)), showWorldOrigin: \(String(describing: showWorldOrigin)), handleTaps: \(String(describing: handleTaps)), handlePans: \(String(describing: handlePans)), handleRotation: \(String(describing: handleRotation)))"
  }
}

/// Payload for `onPanEnd`/`onRotationEnd`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NodeTransformEventMessage: Hashable, CustomStringConvertible {
  var name: String
  var transform: [Double]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NodeTransformEventMessage? {
    let name = pigeonVar_list[0] as! String
    let transform = pigeonVar_list[1] as! [Double]

    return NodeTransformEventMessage(
      name: name,
      transform: transform
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      transform,
    ]
  }
  static func == (lhs: NodeTransformEventMessage, rhs: NodeTransformEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.transform, rhs.transform)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NodeTransformEventMessage")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transform, hasher: &hasher)
  }

  public var description: String {
    return "NodeTransformEventMessage(name: \(String(describing: name)), transform: \(String(describing: transform)))"
  }
}

/// Payload for `onCloudAnchorUploaded`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CloudAnchorUploadedMessage: Hashable, CustomStringConvertible {
  var name: String
  var cloudAnchorId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CloudAnchorUploadedMessage? {
    let name = pigeonVar_list[0] as! String
    let cloudAnchorId = pigeonVar_list[1] as! String

    return CloudAnchorUploadedMessage(
      name: name,
      cloudAnchorId: cloudAnchorId
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      cloudAnchorId,
    ]
  }
  static func == (lhs: CloudAnchorUploadedMessage, rhs: CloudAnchorUploadedMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.cloudAnchorId, rhs.cloudAnchorId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CloudAnchorUploadedMessage")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cloudAnchorId, hasher: &hasher)
  }

  public var description: String {
    return "CloudAnchorUploadedMessage(name: \(String(describing: name)), cloudAnchorId: \(String(describing: cloudAnchorId)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PoseMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return HitTestResultMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return NodeMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return AnchorMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return SessionConfigMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return NodeTransformEventMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return CloudAnchorUploadedMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PoseMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? HitTestResultMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NodeMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AnchorMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? SessionConfigMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NodeTransformEventMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CloudAnchorUploadedMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// The plugin-wide (non-per-instance) API, used only for `getPlatformVersion`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterRealityHostApi {
  func getPlatformVersion() async throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterRealityHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FlutterRealityHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterRealityHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.FlutterRealityHostApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getPlatformVersion()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
  }
}
/// Dart -> native calls scoped to one [ARSessionManager] instance. Each
/// instance registers with a `messageChannelSuffix` derived from its
/// platform view id, replicating today's `arsession_$id` per-instance
/// channel.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ARSessionHostApi {
  func initialize(config: SessionConfigMessage) async throws
  func showPlanes(showPlanes: Bool) async throws
  func dispose() async throws
  func getAnchorPose(anchorId: String) async throws -> PoseMessage
  func getCameraPose() async throws -> PoseMessage
  func snapshot() async throws -> FlutterStandardTypedData
  func disableCamera() async throws
  func enableCamera() async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ARSessionHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ARSessionHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ARSessionHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! SessionConfigMessage
        Task { @MainActor in
          do {
            try await api.initialize(config: configArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let showPlanesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.showPlanes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPlanesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showPlanesArg = args[0] as! Bool
        Task { @MainActor in
          do {
            try await api.showPlanes(showPlanes: showPlanesArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      showPlanesChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.dispose()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let getAnchorPoseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.getAnchorPose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAnchorPoseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let anchorIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getAnchorPose(anchorId: anchorIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAnchorPoseChannel.setMessageHandler(nil)
    }
    let getCameraPoseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.getCameraPose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraPoseChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getCameraPose()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCameraPoseChannel.setMessageHandler(nil)
    }
    let snapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.snapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      snapshotChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.snapshot()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      snapshotChannel.setMessageHandler(nil)
    }
    let disableCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.disableCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disableCameraChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.disableCamera()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disableCameraChannel.setMessageHandler(nil)
    }
    let enableCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.enableCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableCameraChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.enableCamera()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableCameraChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart events scoped to one [ARSessionManager] instance.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ARSessionFlutterApiProtocol {
  @MainActor func onError(message messageArg: String) async throws
  @MainActor func onPlaneDetected(count countArg: Int64) async throws
  @MainActor func onPlaneOrPointTap(hits hitsArg: [HitTestResultMessage]) async throws
}
class ARSessionFlutterApi: ARSessionFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  @MainActor func onError(message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARSessionFlutterApi.onError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onPlaneDetected(count countArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARSessionFlutterApi.onPlaneDetected\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([countArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onPlaneOrPointTap(hits hitsArg: [HitTestResultMessage]) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARSessionFlutterApi.onPlaneOrPointTap\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([hitsArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
/// Dart -> native calls scoped to one [ARObjectManager] instance.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ARObjectHostApi {
  func initialize() async throws
  func addNode(node: NodeMessage) async throws -> Bool
  func addNodeToPlaneAnchor(node: NodeMessage, anchor: AnchorMessage) async throws -> Bool
  func removeNode(name: String) async throws
  func transformationChanged(name: String, transformation: [Double]) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ARObjectHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ARObjectHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ARObjectHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.initialize()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let addNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.addNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeArg = args[0] as! NodeMessage
        Task { @MainActor in
          do {
            let result = try await api.addNode(node: nodeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      addNodeChannel.setMessageHandler(nil)
    }
    let addNodeToPlaneAnchorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.addNodeToPlaneAnchor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addNodeToPlaneAnchorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeArg = args[0] as! NodeMessage
        let anchorArg = args[1] as! AnchorMessage
        Task { @MainActor in
          do {
            let result = try await api.addNodeToPlaneAnchor(node: nodeArg, anchor: anchorArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      addNodeToPlaneAnchorChannel.setMessageHandler(nil)
    }
    let removeNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.removeNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.removeNode(name: nameArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeNodeChannel.setMessageHandler(nil)
    }
    let transformationChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.transformationChanged\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transformationChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let transformationArg = args[1] as! [Double]
        Task { @MainActor in
          do {
            try await api.transformationChanged(name: nameArg, transformation: transformationArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      transformationChangedChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart events scoped to one [ARObjectManager] instance.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ARObjectFlutterApiProtocol {
  @MainActor func onError(message messageArg: String) async throws
  @MainActor func onNodeTap(names namesArg: [String?]) async throws
  @MainActor func onPanStart(name nameArg: String) async throws
  @MainActor func onPanChange(name nameArg: String) async throws
  @MainActor func onPanEnd(event eventArg: NodeTransformEventMessage) async throws
  @MainActor func onRotationStart(name nameArg: String) async throws
  @MainActor func onRotationChange(name nameArg: String) async throws
  @MainActor func onRotationEnd(event eventArg: NodeTransformEventMessage) async throws
}
class ARObjectFlutterApi: ARObjectFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  @MainActor func onError(message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onNodeTap(names namesArg: [String?]) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onNodeTap\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([namesArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onPanStart(name nameArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onPanStart\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([nameArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onPanChange(name nameArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onPanChange\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([nameArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onPanEnd(event eventArg: NodeTransformEventMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onPanEnd\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onRotationStart(name nameArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onRotationStart\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([nameArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onRotationChange(name nameArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onRotationChange\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([nameArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onRotationEnd(event eventArg: NodeTransformEventMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onRotationEnd\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
/// Dart -> native calls scoped to one [ARAnchorManager] instance.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ARAnchorHostApi {
  func initGoogleCloudAnchorMode() async throws -> Bool
  func addAnchor(anchor: AnchorMessage) async throws -> Bool
  func removeAnchor(name: String) async throws
  func uploadAnchor(name: String) async throws -> Bool
  func downloadAnchor(cloudAnchorId: String) async throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ARAnchorHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ARAnchorHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ARAnchorHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initGoogleCloudAnchorModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.initGoogleCloudAnchorMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initGoogleCloudAnchorModeChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.initGoogleCloudAnchorMode()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initGoogleCloudAnchorModeChannel.setMessageHandler(nil)
    }
    let addAnchorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.addAnchor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAnchorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let anchorArg = args[0] as! AnchorMessage
        Task { @MainActor in
          do {
            let result = try await api.addAnchor(anchor: anchorArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAnchorChannel.setMessageHandler(nil)
    }
    let removeAnchorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.removeAnchor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAnchorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.removeAnchor(name: nameArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAnchorChannel.setMessageHandler(nil)
    }
    let uploadAnchorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.uploadAnchor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      uploadAnchorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.uploadAnchor(name: nameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      uploadAnchorChannel.setMessageHandler(nil)
    }
    let downloadAnchorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.downloadAnchor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadAnchorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cloudAnchorIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.downloadAnchor(cloudAnchorId: cloudAnchorIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadAnchorChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart events scoped to one [ARAnchorManager] instance.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ARAnchorFlutterApiProtocol {
  @MainActor func onError(message messageArg: String) async throws
  @MainActor func onCloudAnchorUploaded(event eventArg: CloudAnchorUploadedMessage) async throws
  /// Native waits for Dart's returned anchor name before completing the
  /// download.
  @MainActor func onAnchorDownloadSuccess(anchor anchorArg: AnchorMessage) async throws -> String
}
class ARAnchorFlutterApi: ARAnchorFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  @MainActor func onError(message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARAnchorFlutterApi.onError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onCloudAnchorUploaded(event eventArg: CloudAnchorUploadedMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARAnchorFlutterApi.onCloudAnchorUploaded\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// Native waits for Dart's returned anchor name before completing the
  /// download.
  @MainActor func onAnchorDownloadSuccess(anchor anchorArg: AnchorMessage) async throws -> String {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_reality.ARAnchorFlutterApi.onAnchorDownloadSuccess\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([anchorArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else if listResponse[0] == nil || listResponse[0] is NSNull {
          continuation.resume(throwing: PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: ""))
        } else {
          let result = listResponse[0] as! String
          continuation.resume(returning: result)
        }
      }
    }
  }
}
