// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.flutterreality.flutter_reality

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * A rigid transform, flattened as a 16-element row-major matrix
 * (matches `Matrix4.storage` / `Matrix4.fromList`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PoseMessage (
  val matrix: List<Double>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PoseMessage {
      val matrix = pigeonVar_list[0] as List<Double>
      return PoseMessage(matrix)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      matrix,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PoseMessage
    return MessagesPigeonUtils.deepEquals(this.matrix, other.matrix)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.matrix)
    return result
  }
  override fun toString(): String {
    return "PoseMessage(matrix=$matrix)"
  }
}

/**
 * One entry from an `ARSessionManager.onPlaneOrPointTap` hit test.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HitTestResultMessage (
  /** Mirrors `ARHitTestResultType` (0 = undefined, 1 = plane, 2 = point). */
  val type: Long,
  val distance: Double,
  val worldTransform: List<Double>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HitTestResultMessage {
      val type = pigeonVar_list[0] as Long
      val distance = pigeonVar_list[1] as Double
      val worldTransform = pigeonVar_list[2] as List<Double>
      return HitTestResultMessage(type, distance, worldTransform)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      distance,
      worldTransform,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HitTestResultMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.distance, other.distance) && MessagesPigeonUtils.deepEquals(this.worldTransform, other.worldTransform)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.distance)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.worldTransform)
    return result
  }
  override fun toString(): String {
    return "HitTestResultMessage(type=$type, distance=$distance, worldTransform=$worldTransform)"
  }
}

/**
 * Mirrors `ARNode.toMap()` / `ARNode.fromMap()`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NodeMessage (
  /** Mirrors `NodeType.index`. */
  val type: Long,
  val name: String,
  val transformation: List<Double>,
  val uri: String? = null,
  val data: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NodeMessage {
      val type = pigeonVar_list[0] as Long
      val name = pigeonVar_list[1] as String
      val transformation = pigeonVar_list[2] as List<Double>
      val uri = pigeonVar_list[3] as String?
      val data = pigeonVar_list[4] as Map<String?, Any?>?
      return NodeMessage(type, name, transformation, uri, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      name,
      transformation,
      uri,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NodeMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.transformation, other.transformation) && MessagesPigeonUtils.deepEquals(this.uri, other.uri) && MessagesPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transformation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.data)
    return result
  }
  override fun toString(): String {
    return "NodeMessage(type=$type, name=$name, transformation=$transformation, uri=$uri, data=$data)"
  }
}

/**
 * Mirrors `ARAnchor.toJson()` / `ARAnchor.fromJson()` (currently only
 * `ARPlaneAnchor` is implemented natively; `ARUnkownAnchor` is a
 * forward-compatible placeholder for anchor types future native code may
 * add, hence the mostly-nullable fields below).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AnchorMessage (
  /** Mirrors `AnchorType.index` (0 = plane). */
  val type: Long,
  val name: String,
  val transformation: List<Double>,
  val childNodes: List<String?>? = null,
  val cloudAnchorId: String? = null,
  val ttl: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnchorMessage {
      val type = pigeonVar_list[0] as Long
      val name = pigeonVar_list[1] as String
      val transformation = pigeonVar_list[2] as List<Double>
      val childNodes = pigeonVar_list[3] as List<String?>?
      val cloudAnchorId = pigeonVar_list[4] as String?
      val ttl = pigeonVar_list[5] as Long?
      return AnchorMessage(type, name, transformation, childNodes, cloudAnchorId, ttl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      name,
      transformation,
      childNodes,
      cloudAnchorId,
      ttl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AnchorMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.transformation, other.transformation) && MessagesPigeonUtils.deepEquals(this.childNodes, other.childNodes) && MessagesPigeonUtils.deepEquals(this.cloudAnchorId, other.cloudAnchorId) && MessagesPigeonUtils.deepEquals(this.ttl, other.ttl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transformation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.childNodes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cloudAnchorId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ttl)
    return result
  }
  override fun toString(): String {
    return "AnchorMessage(type=$type, name=$name, transformation=$transformation, childNodes=$childNodes, cloudAnchorId=$cloudAnchorId, ttl=$ttl)"
  }
}

/**
 * Arguments for `ARSessionManager.onInitialize`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SessionConfigMessage (
  val showAnimatedGuide: Boolean,
  val showFeaturePoints: Boolean,
  /** Mirrors `PlaneDetectionConfig.index`. */
  val planeDetectionConfig: Long,
  val showPlanes: Boolean,
  val customPlaneTexturePath: String? = null,
  val showWorldOrigin: Boolean,
  val handleTaps: Boolean,
  val handlePans: Boolean,
  val handleRotation: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionConfigMessage {
      val showAnimatedGuide = pigeonVar_list[0] as Boolean
      val showFeaturePoints = pigeonVar_list[1] as Boolean
      val planeDetectionConfig = pigeonVar_list[2] as Long
      val showPlanes = pigeonVar_list[3] as Boolean
      val customPlaneTexturePath = pigeonVar_list[4] as String?
      val showWorldOrigin = pigeonVar_list[5] as Boolean
      val handleTaps = pigeonVar_list[6] as Boolean
      val handlePans = pigeonVar_list[7] as Boolean
      val handleRotation = pigeonVar_list[8] as Boolean
      return SessionConfigMessage(showAnimatedGuide, showFeaturePoints, planeDetectionConfig, showPlanes, customPlaneTexturePath, showWorldOrigin, handleTaps, handlePans, handleRotation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      showAnimatedGuide,
      showFeaturePoints,
      planeDetectionConfig,
      showPlanes,
      customPlaneTexturePath,
      showWorldOrigin,
      handleTaps,
      handlePans,
      handleRotation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SessionConfigMessage
    return MessagesPigeonUtils.deepEquals(this.showAnimatedGuide, other.showAnimatedGuide) && MessagesPigeonUtils.deepEquals(this.showFeaturePoints, other.showFeaturePoints) && MessagesPigeonUtils.deepEquals(this.planeDetectionConfig, other.planeDetectionConfig) && MessagesPigeonUtils.deepEquals(this.showPlanes, other.showPlanes) && MessagesPigeonUtils.deepEquals(this.customPlaneTexturePath, other.customPlaneTexturePath) && MessagesPigeonUtils.deepEquals(this.showWorldOrigin, other.showWorldOrigin) && MessagesPigeonUtils.deepEquals(this.handleTaps, other.handleTaps) && MessagesPigeonUtils.deepEquals(this.handlePans, other.handlePans) && MessagesPigeonUtils.deepEquals(this.handleRotation, other.handleRotation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showAnimatedGuide)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showFeaturePoints)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.planeDetectionConfig)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showPlanes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.customPlaneTexturePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showWorldOrigin)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handleTaps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handlePans)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handleRotation)
    return result
  }
  override fun toString(): String {
    return "SessionConfigMessage(showAnimatedGuide=$showAnimatedGuide, showFeaturePoints=$showFeaturePoints, planeDetectionConfig=$planeDetectionConfig, showPlanes=$showPlanes, customPlaneTexturePath=$customPlaneTexturePath, showWorldOrigin=$showWorldOrigin, handleTaps=$handleTaps, handlePans=$handlePans, handleRotation=$handleRotation)"
  }
}

/**
 * Payload for `onPanEnd`/`onRotationEnd`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NodeTransformEventMessage (
  val name: String,
  val transform: List<Double>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NodeTransformEventMessage {
      val name = pigeonVar_list[0] as String
      val transform = pigeonVar_list[1] as List<Double>
      return NodeTransformEventMessage(name, transform)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      transform,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NodeTransformEventMessage
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.transform, other.transform)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transform)
    return result
  }
  override fun toString(): String {
    return "NodeTransformEventMessage(name=$name, transform=$transform)"
  }
}

/**
 * Payload for `onCloudAnchorUploaded`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CloudAnchorUploadedMessage (
  val name: String,
  val cloudAnchorId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CloudAnchorUploadedMessage {
      val name = pigeonVar_list[0] as String
      val cloudAnchorId = pigeonVar_list[1] as String
      return CloudAnchorUploadedMessage(name, cloudAnchorId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      cloudAnchorId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CloudAnchorUploadedMessage
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.cloudAnchorId, other.cloudAnchorId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cloudAnchorId)
    return result
  }
  override fun toString(): String {
    return "CloudAnchorUploadedMessage(name=$name, cloudAnchorId=$cloudAnchorId)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PoseMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HitTestResultMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NodeMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnchorMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionConfigMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NodeTransformEventMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CloudAnchorUploadedMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PoseMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is HitTestResultMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NodeMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AnchorMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SessionConfigMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NodeTransformEventMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CloudAnchorUploadedMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * The plugin-wide (non-per-instance) API, used only for `getPlatformVersion`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface FlutterRealityHostApi {
  suspend fun getPlatformVersion(): String

  companion object {
    /** The codec used by FlutterRealityHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `FlutterRealityHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterRealityHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.FlutterRealityHostApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getPlatformVersion())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Dart -> native calls scoped to one [ARSessionManager] instance. Each
 * instance registers with a `messageChannelSuffix` derived from its
 * platform view id, replicating today's `arsession_$id` per-instance
 * channel.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ARSessionHostApi {
  suspend fun initialize(config: SessionConfigMessage)
  suspend fun showPlanes(showPlanes: Boolean)
  suspend fun dispose()
  suspend fun getAnchorPose(anchorId: String): PoseMessage
  suspend fun getCameraPose(): PoseMessage
  suspend fun snapshot(): ByteArray
  suspend fun disableCamera()
  suspend fun enableCamera()

  companion object {
    /** The codec used by ARSessionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ARSessionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ARSessionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as SessionConfigMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.initialize(configArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.showPlanes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val showPlanesArg = args[0] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.showPlanes(showPlanesArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.dispose()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.getAnchorPose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val anchorIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getAnchorPose(anchorIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.getCameraPose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getCameraPose())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.snapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.snapshot())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.disableCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.disableCamera()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARSessionHostApi.enableCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.enableCamera()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart events scoped to one [ARSessionManager] instance.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ARSessionFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ARSessionFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  suspend fun onError(messageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARSessionFlutterApi.onError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(messageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onPlaneDetected(countArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARSessionFlutterApi.onPlaneDetected$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(countArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onPlaneOrPointTap(hitsArg: List<HitTestResultMessage>)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARSessionFlutterApi.onPlaneOrPointTap$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(hitsArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/**
 * Dart -> native calls scoped to one [ARObjectManager] instance.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ARObjectHostApi {
  suspend fun initialize()
  suspend fun addNode(node: NodeMessage): Boolean
  suspend fun addNodeToPlaneAnchor(node: NodeMessage, anchor: AnchorMessage): Boolean
  suspend fun removeNode(name: String)
  suspend fun transformationChanged(name: String, transformation: List<Double>)

  companion object {
    /** The codec used by ARObjectHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ARObjectHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ARObjectHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.initialize()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.addNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeArg = args[0] as NodeMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.addNode(nodeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.addNodeToPlaneAnchor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeArg = args[0] as NodeMessage
            val anchorArg = args[1] as AnchorMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.addNodeToPlaneAnchor(nodeArg, anchorArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.removeNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.removeNode(nameArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARObjectHostApi.transformationChanged$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val transformationArg = args[1] as List<Double>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.transformationChanged(nameArg, transformationArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart events scoped to one [ARObjectManager] instance.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ARObjectFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ARObjectFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  suspend fun onError(messageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(messageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onNodeTap(namesArg: List<String?>)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onNodeTap$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(namesArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onPanStart(nameArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onPanStart$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(nameArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onPanChange(nameArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onPanChange$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(nameArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onPanEnd(eventArg: NodeTransformEventMessage)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onPanEnd$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onRotationStart(nameArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onRotationStart$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(nameArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onRotationChange(nameArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onRotationChange$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(nameArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onRotationEnd(eventArg: NodeTransformEventMessage)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARObjectFlutterApi.onRotationEnd$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/**
 * Dart -> native calls scoped to one [ARAnchorManager] instance.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ARAnchorHostApi {
  suspend fun initGoogleCloudAnchorMode(): Boolean
  suspend fun addAnchor(anchor: AnchorMessage): Boolean
  suspend fun removeAnchor(name: String)
  suspend fun uploadAnchor(name: String): Boolean
  suspend fun downloadAnchor(cloudAnchorId: String): Boolean

  companion object {
    /** The codec used by ARAnchorHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ARAnchorHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ARAnchorHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.initGoogleCloudAnchorMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.initGoogleCloudAnchorMode())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.addAnchor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val anchorArg = args[0] as AnchorMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.addAnchor(anchorArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.removeAnchor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.removeAnchor(nameArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.uploadAnchor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.uploadAnchor(nameArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reality.ARAnchorHostApi.downloadAnchor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloudAnchorIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.downloadAnchor(cloudAnchorIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart events scoped to one [ARAnchorManager] instance.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ARAnchorFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ARAnchorFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  suspend fun onError(messageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARAnchorFlutterApi.onError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(messageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onCloudAnchorUploaded(eventArg: CloudAnchorUploadedMessage)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARAnchorFlutterApi.onCloudAnchorUploaded$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /**
   * Native waits for Dart's returned anchor name before completing the
   * download.
   */
  suspend fun onAnchorDownloadSuccess(anchorArg: AnchorMessage): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_reality.ARAnchorFlutterApi.onAnchorDownloadSuccess$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(anchorArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
